### ISSUE TITLE
Diagram Design

### ISSUE THREAD

**Issue by pjhampton** [wxs/keras-mnist-tutorial#2]
This is a really random question @wxs, but what tool did you use to create the diagram [figure.png](https://github.com/wxs/keras-mnist-tutorial/blob/master/figure.png)? I need to create similar diagrams for lecture notes and I really like this.

**Comment by wxs** [comment]
Oh I _wish_ there was a good tool. I actually wrote a quick program in Processing to write the edges and nodes out to a PDF which I then imported into Illustrator / Inkscape to add the text labels.

No points for code quality on this, it was just a quick hack, but here's the code if you're interested:

https://gist.github.com/wxs/757aa2b4c7cce635c8175c973330802a

**Comment by pjhampton** [comment]
Thanks so much for replying and the code! ❤️
